#!/bin/bash
# Download a video from youtube

if [ -z $1 ] ; then
  echo "Usage: tube [720] https://youtube......video"
  exit
fi

UTIL=youtube-dl
UTIL=yt-dlp
qual=1080

cd /ln/hh/yt 2>/dev/null || cd /ln/dwn
if ! [ -z $2 ]
then
  qual=$1
  url=$2
elif ! [ -z $1 ]
then
  url=$1
fi

#$UTIL --no-mtime -f "bestvideo[height<=$1]+bestaudio" $url
#$UTIL --no-mtime -f "bestvideo[height<=1080]+bestaudio" $url

$UTIL --no-mtime -f "bestvideo[height<=$qual]+bestaudio" $url
EXCOD=$?
sleep .1

# outnamewild="$PWD"/*"$(echo "$url" | cut -d = -f2)"*
# outname=$(ls $utnamewild)

# ls -at /ln/dwn  | grep "\[...........\]\."
outname=$(ls -ath  /ln/dwn/*\[*\].* | head -1)


if [[ $EXCOD -eq 0 ]]; then
    # Print info about file
    echo .
    echo -e "'output is:'\n echo \"$outname\""
    # ls -lh "$outname"
    du -h "$outname" | cut -f1
    echo .
    mediainfo "$outname" | grep 'pixels\|bits\|Video\|Audio\|Format  \|rate'
fi

cd - &>/dev/null

